name: Appium

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: ⚙️ Install and start Appium
        shell: pwsh  
        run: |
          npm install -g appium
          appium driver install windows
          appium --version
          dir "$env:APPDATA\npm"
          
    # start cmd /k '%AppData%\npm\appium.cmd'
    # Start-Process -NoNewWindow -FilePath "$env:APPDATA\npm\appium.cmd"
