name: Appium

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: ⚙️ Install and start Appium
        shell: cmd 
        run: |
          npm install -g appium
          appium

    # "%AppData%\npm\appium.cmd" --version
    # start cmd /k "%AppData%\npm\appium.cmd"

          
    # appium driver install windows
    # start cmd /k '%AppData%\npm\appium.cmd'
    # Start-Process -NoNewWindow -FilePath "$env:APPDATA\npm\appium.cmd"
