name: Appium

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: ⚙️ Add npm global bin to PATH
        shell: pwsh  
        run: echo "$env:APPDATA\npm" | Out-File -Append -Encoding ascii $env:GITHUB_PATH

      - name: ⚙️ Install and start Appium
        shell: pwsh  
        run: |
          npm install -g appium
          appium driver install windows
          Start-Process -NoNewWindow -FilePath "appium"
