name: Appium

on:
  # push:
  #   branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025

    steps:
      - name: ⚙️ Install Appium Server
        shell: pwsh 
        run: |
          npm install -g appium
          appium --version
          
      # - name: Start Appium Server
      #   run: start /B appium
      #   shell: cmd

      - name: Start Appium Server
        run: appium &
        shell: bash

      - name: Check if Appium is running
        shell: pwsh  
        run: |
          Test-NetConnection -ComputerName localhost -Port 4723
        
      
      - name: Check if Appium is running
        shell: bash  
        run: |
          curl --fail http://localhost:4723/status
        
    # Start-Process -FilePath "pwsh" -ArgumentList ". '(Get-Command appium).Source'"
    # Start-Process -FilePath "pwsh" -ArgumentList "-File `"(Get-Command appium).Source`"" -WindowStyle Hidden
    # Start-Process -FilePath "pwsh" -ArgumentList ". '(Get-Command appium).Source'"

    # "%AppData%\npm\appium.cmd" --version
    # start cmd /k "%AppData%\npm\appium.cmd"

    # appium driver install windows
    # start cmd /k '%AppData%\npm\appium.cmd'
    # Start-Process -NoNewWindow -FilePath "$env:APPDATA\npm\appium.cmd"
    
    # shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
    # Start-Process -FilePath "powershell.exe" -ArgumentList "-NoProfile -ExecutionPolicy Bypass -File `"$appiumPath`"" -WindowStyle Hidden